# Travis CI configuration file for a WordPoints extension.

language: php

php:
    - 7.2
    - 7.1
    - 7.0
    - 5.6
    - 5.5
    - 5.4

env:
    - TRAVISCI_RUN=codesniff
    - TRAVISCI_RUN=phpunit WP_VERSION=develop WORDPOINTS_VERSION=develop
    - TRAVISCI_RUN=phpunit WP_VERSION=4.8 WORDPOINTS_VERSION=develop
    - TRAVISCI_RUN=phpunit WP_VERSION=4.7 WORDPOINTS_VERSION=develop

dist: trusty

sudo: false

addons:
  apt:
    packages:
      # Needed for `xmllint`.
      - libxml2-utils

matrix:
  include:
    # Use Ubuntu Precise because Trusty doesn't support PHP 5.2 or 5.3.
    - php: 5.3
      dist: precise
      env: TRAVISCI_RUN=phpunit WP_VERSION=develop WORDPOINTS_VERSION=develop
    - php: 5.3
      dist: precise
      env: TRAVISCI_RUN=phpunit WP_VERSION=4.8 WORDPOINTS_VERSION=develop
    - php: 5.3
      dist: precise
      env: TRAVISCI_RUN=phpunit WP_VERSION=4.7 WORDPOINTS_VERSION=develop
    # Only run nightly against trunk.
    - php: nightly
      env: TRAVISCI_RUN=phpunit WP_VERSION=develop
  exclude:
    # The codesniff pass only needs to be run once.
    - php: 7.2
      env: TRAVISCI_RUN=codesniff
    - php: 7.0
      env: TRAVISCI_RUN=codesniff
    - php: 5.6
      env: TRAVISCI_RUN=codesniff
    - php: 5.5
      env: TRAVISCI_RUN=codesniff
    - php: 5.4
      env: TRAVISCI_RUN=codesniff
  allow_failures:
    - php: nightly
    - php: 7.2
  fast_finish: true

before_install:
    - openssl aes-256-cbc -K $encrypted_0d261e9bbce3_key -iv $encrypted_0d261e9bbce3_iv -in wpdatatables.zip.enc -out wpdatatables.zip -d

before_script:
    - export WORDPOINTS_PROJECT_TYPE=extension
    - export DEV_LIB_PATH=dev-lib
    - if [ -e .wordpoints-dev-lib-config.sh ]; then source .wordpoints-dev-lib-config.sh; fi
    - source $DEV_LIB_PATH/travis/before_script.sh

script:
    - codesniff-php-syntax
    - codesniff-php-autoloaders
    - codesniff-phpcs
    - codesniff-strings
    - codesniff-dittography
    - codesniff-jshint
    - codesniff-l10n
    - codesniff-xmllint
    - codesniff-bash
    - codesniff-symlinks
    - phpunit-basic
    - phpunit-ms
    - phpunit-ms-network
    - phpunit-uninstall
    - phpunit-ms-uninstall
    - phpunit-ms-network-uninstall
    - WORDPOINTS_ONLY_UNINSTALL_EXTENSION=1 phpunit-uninstall
    - WORDPOINTS_ONLY_UNINSTALL_EXTENSION=1 phpunit-ms-uninstall
    - WORDPOINTS_ONLY_UNINSTALL_EXTENSION=1 phpunit-ms-network-uninstall
    - phpunit-ajax
    - phpunit-ms-ajax
    - phpunit-ms-network-ajax
    - wpcept-run

after_script:
    - source $DEV_LIB_PATH/travis/after_script.sh
